# Generated by Django 3.1.4 on 2021-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
