# Generated by Django 3.1.4 on 2021-01-11 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Pendente', 'Pendente')], default='Pendente', max_length=30)),
                ('description', models.TextField(null=True)),
                ('ended_in', models.DateTimeField(null=True)),
                ('files', models.FileField(blank=True, max_length=5000, null=True, upload_to=home.models.Tickets.user_directory_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sectortype')),
                ('sort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
            ],
        ),
    ]
