# Generated by Django 3.1.4 on 2021-01-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_operatoraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorAccount',
        ),
    ]
