# Generated by Django 3.1.4 on 2021-01-02 05:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210101_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='imagem',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to=home.models.Tickets.user_directory_path),
        ),
    ]
