# Generated by Django 3.1.4 on 2021-01-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_operatoraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoReply',
        ),
    ]
