# Generated by Django 3.1.4 on 2021-03-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tickets'),
        ),
    ]
