# Generated by Django 3.1.4 on 2021-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notification_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='viwed',
            new_name='viewed',
        ),
    ]
